const SITE_CONFIG={
 name:'Arpita Baby',openingLine:'somewhere in the quiet...',introHeader:'Some moments are small...',photo:'assets/images/our-photo.jpg',photoCaption:'This is us — the part I keep coming back to.',finalQuestion:'If I could keep one feeling from us forever, what would it be?',
 finalAnswerOptions:['The way your laugh settles everything.','The calm that exists when we are together.','The feeling that the future is brighter with you in it.'],
 finalMessage:['Some people fill a room. You quietly rearrange the whole world around you, and somehow no one notices until they realize nothing feels the same without you in it.','I do not know exactly what our future holds — but I know I want every slow morning, every quiet drive, and every dream we have not spoken out loud to be part of it.','This was never really about eight questions. It was just an excuse to spend a little more time thinking about you, and to make a place for all the quiet love that keeps growing between us.'],
 secretMessage:'Made for Arpita Baby, on purpose, with all the quiet details.',
 memoryCards:[
  {title:'Little things',items:['The way you make even silence feel warm.','The way a small look can say everything.']},
  {title:'Moments I remember',items:['The calm after a long day when it feels easy to just be near you.','The kind of laughter that makes everything lighter.']},
  {title:'Things I love',items:['Your gentleness.','The sincerity in everything you do.']},
  {title:'Things that make me smile',items:['Your expression before you laugh.','How naturally you make a room feel softer.']}
 ],
 futureCards:[
  {title:'Somewhere to go',items:['A place no one else knows about.','A quiet road trip with no rush.']},
  {title:'Something to try',items:['A late-night walk with nowhere to be.','A day that starts slow and ends in laughter.']},
  {title:'A memory to make',items:['A sunrise we watched together.','A tiny tradition that belongs only to us.']},
  {title:'A dream to hold onto',items:['A life that feels gentle and honest.','A future where we keep choosing each other.']}
 ],
 questions:[
  {text:'Which moment with me would you secretly replay if you could?',options:[{text:'The quiet one that felt like home.',mood:'quiet'},{text:'The one where we laughed so hard we forgot the world.',mood:'wild'},{text:'The tiny moment that made me feel closer to you.',mood:'ember'}]},
  {text:'What is one little thing I do that somehow always makes you smile?',options:[{text:'The way you make the room feel softer.',mood:'quiet'},{text:'That look you get when you are happy around me.',mood:'ember'},{text:'The way you are completely yourself with me.',mood:'wild'}]},
  {text:'Which of our silly moments still makes you laugh the most?',options:[{text:'The one that changed the mood in an instant.',mood:'wild'},{text:'The one where we laughed for no real reason at all.',mood:'ember'},{text:'The one where neither of us wanted it to end.',mood:'quiet'}]},
  {text:'Which moment between us felt unexpectedly special?',options:[{text:'The quiet one that said more than words ever could.',mood:'quiet'},{text:'The one where I felt unusually close to you.',mood:'ember'},{text:'The one that felt like a secret only we were sharing.',mood:'wild'}]},
  {text:'If we could relive one kind of day together, which would you choose?',options:[{text:'A slow day with no plans and all the time in the world.',mood:'quiet'},{text:'A day full of movement, laughter, and little adventures.',mood:'wild'},{text:'A day that felt dreamy, cinematic, and completely ours.',mood:'ember'}]},
  {text:'When do you feel closest to me?',options:[{text:'When we are just quiet together.',mood:'quiet'},{text:'When we are talking and everything feels honest.',mood:'ember'},{text:'When it feels like the whole world disappears for a moment.',mood:'wild'}]},
  {text:'If we could disappear somewhere together tomorrow, where would you want us to go?',options:[{text:'Somewhere calm, tucked away, and private.',mood:'quiet'},{text:'Somewhere warm and full of life and stories.',mood:'ember'},{text:'Somewhere wild enough to feel like a dream.',mood:'wild'}]},
  {text:'What is one memory you still want us to make someday?',options:[{text:'A sunrise we watched together, without rushing.',mood:'quiet'},{text:'A late-night adventure that felt a little unreal.',mood:'wild'},{text:'A tradition that belongs to us and no one else.',mood:'ember'}]}
 ]
};

(()=>{
 'use strict';
 const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],body=document.body;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,touch=matchMedia('(hover:none)').matches;
 const hues={ember:28,quiet:260,wild:8};
 const scenes=['scene-dark','scene-story','scene-journey','scene-memory','scene-someday','scene-hush','scene-final'];
 let currentScene=0;

 const ParticleField=(()=>{const canvas=$('#ember-field'),ctx=canvas.getContext('2d');let p=[],w=0,h=0,d=1,hue=30;function resize(){d=Math.min(devicePixelRatio||1,2);w=canvas.width=innerWidth*d;h=canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px'}function seed(){p=Array.from({length:reduced?0:innerWidth<700?24:55},()=>({x:Math.random()*w,y:Math.random()*h,r:(Math.random()*1.4+.35)*d,s:(Math.random()*.3+.04)*d,a:Math.random()*.34+.07}));}function draw(){ctx.clearRect(0,0,w,h);p.forEach(x=>{x.y-=x.s;x.x+=Math.sin(x.y*.002)*.08*d;if(x.y<-10){x.y=h+10;x.x=Math.random()*w}ctx.beginPath();ctx.fillStyle=`hsla(${hue},68%,68%,${x.a})`;ctx.arc(x.x,x.y,x.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(draw)}function setHue(v){hue+=(v-hue)*.06}function init(){resize();seed();addEventListener('resize',()=>{resize();seed()},{passive:true});if(!reduced)draw()}return{init,setHue}})();

 const Cursor=(()=>{let tx=innerWidth/2,ty=innerHeight/2,cx=tx,cy=ty,run=false;function move(x,y){tx=x;ty=y;body.classList.add('cursor-ready');if(!run&&!reduced){run=true;(function loop(){cx+=(tx-cx)*.09;cy+=(ty-cy)*.09;document.documentElement.style.setProperty('--glow-x',cx+'px');document.documentElement.style.setProperty('--glow-y',cy+'px');requestAnimationFrame(loop)})()}else{document.documentElement.style.setProperty('--glow-x',x+'px');document.documentElement.style.setProperty('--glow-y',y+'px')}}function init(){if(reduced)return;addEventListener('pointermove',e=>move(e.clientX,e.clientY),{passive:true});addEventListener('touchstart',e=>{if(e.touches[0])move(e.touches[0].clientX,e.touches[0].clientY)},{passive:true})}return{init}})();

 function reveal(root){$$('[data-reveal]',root).forEach((el,i)=>setTimeout(()=>el.classList.add('is-in'),120+i*160));const title=$('.title-rule',root);if(title)setTimeout(()=>title.classList.add('is-in'),420)}
 function transition(cb){if(reduced){cb();return}const layer=$('#transition-layer'),ring=$('#transition-layer span');layer.style.transition='none';layer.style.opacity=0;ring.style.opacity=0;ring.style.transform='scale(.4)';requestAnimationFrame(()=>{layer.style.transition='opacity .55s ease';ring.style.transition='transform .9s ease,opacity .45s ease';layer.style.opacity=1;ring.style.opacity=1;ring.style.transform='scale(1.5)';setTimeout(()=>{cb();setTimeout(()=>{layer.style.opacity=0;ring.style.opacity=0},180)},560)})}
 function showScene(from,to){const a=$(from),b=$(to);if(!a||!b)return;a.classList.add('scene--leaving');setTimeout(()=>{a.classList.remove('scene--active','scene--leaving');b.classList.add('scene--active','scene--entering');setTimeout(()=>b.classList.remove('scene--entering'),900)},reduced?0:620)}
 function goTo(id){const idx=scenes.indexOf(id);if(idx<0||idx===currentScene)return;const from='#'+scenes[currentScene],to='#'+id;transition(()=>showScene(from,to));currentScene=idx;$('#top-progress span').style.width=((idx/(scenes.length-1))*100)+'%';body.classList.toggle('scene-final-active',id==='scene-final');if(id==='scene-journey')body.classList.add('scene-journey-active');setTimeout(()=>{const el=$(to);reveal(el);if(id==='scene-memory'||id==='scene-someday')el.scrollTop=0},reduced?20:750)}

 const Opening=(()=>{let done=false;function discover(){if(done)return;done=true;body.classList.add('discovering');reveal($('#scene-dark'))}function init(){if(reduced||touch)setTimeout(discover,350);else{addEventListener('pointermove',discover,{once:true});addEventListener('keydown',discover,{once:true});setTimeout(discover,4200)}$('#begin-btn').addEventListener('click',()=>{body.classList.add('began');goTo('scene-story')})}return{init}})();

 const Journey=(()=>{const stage=$('#question-stage'),fill=$('#progress-fill'),count=$('#q-current'),total=$('#q-total'),whisper=$('#journey-whisper');let index=0,busy=false;const tally={ember:0,quiet:0,wild:0};function render(){total.textContent=String(SITE_CONFIG.questions.length).padStart(2,'0');SITE_CONFIG.questions.forEach((q,i)=>{const wrap=document.createElement('div');wrap.className='question'+(!i?' is-current':'');wrap.dataset.index=i;const n=document.createElement('p');n.className='question-number';n.textContent=`${String(i+1).padStart(2,'0')} / ${String(SITE_CONFIG.questions.length).padStart(2,'0')}`;const h=document.createElement('h2');h.className='question-text';h.textContent=q.text;const list=document.createElement('ul');list.className='options';q.options.forEach(o=>{const li=document.createElement('li'),b=document.createElement('button');b.type='button';b.className='option-btn';b.dataset.mood=o.mood;b.innerHTML=`<span>${o.text}</span><span class="option-btn__mark">— chosen</span>`;b.addEventListener('click',()=>answer(i,o.mood,b,list));li.appendChild(b);list.appendChild(li)});wrap.append(n,h,list);stage.appendChild(wrap)})}function answer(i,mood,selected,list){if(busy)return;busy=true;$$('.option-btn',list).forEach(b=>{b.disabled=true;if(b!==selected)b.classList.add('is-dimmed')});selected.classList.add('is-selected');tally[mood]++;ParticleField.setHue(hues[mood]);const lines={ember:['the light warms, just slightly.','somewhere, a candle catches.'],quiet:['a hush settles in.','everything slows, just for a second.'],wild:['something stirs in the dark.','the night leans in.']};whisper.textContent=lines[mood][Math.floor(Math.random()*2)];whisper.classList.add('is-in');setTimeout(()=>{whisper.classList.remove('is-in');advance(i)},reduced?250:850)}function advance(i){const cur=$(`.question[data-index="${i}"]`,stage);if(i===SITE_CONFIG.questions.length-1){cur.classList.add('is-leaving');setTimeout(()=>goTo('scene-memory'),reduced?0:500);return}const next=$(`.question[data-index="${i+1}"]`,stage);cur.classList.add('is-leaving');setTimeout(()=>{cur.classList.remove('is-current','is-leaving');next.classList.add('is-current');index=i+1;count.textContent=String(index+1).padStart(2,'0');fill.style.width=((index+1)/SITE_CONFIG.questions.length*100)+'%';busy=false},reduced?0:480)}function init(){render();fill.style.width=(100/SITE_CONFIG.questions.length)+'%'}return{init,tally:()=>tally}})();

 function renderCards(id,cards,klass){const grid=$(id);cards.forEach((card,i)=>{const a=document.createElement('article');a.className=klass;a.style.animationDelay=(i*.12)+'s';a.innerHTML=`<h3>${card.title}</h3><ul>${card.items.map(x=>`<li>${x}</li>`).join('')}</ul>`;grid.appendChild(a)})}

 const Photo=(()=>{const modal=$('#photo-modal'),close=$('#photo-modal-close');function open(){modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');body.classList.add('modal-open');close.focus()}function shut(){modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');body.classList.remove('modal-open')}function init(){const cards=$$('[data-photo-card]');cards.forEach(c=>c.addEventListener('click',open));close.addEventListener('click',shut);modal.addEventListener('click',e=>{if(e.target===modal)shut()});addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('is-open'))shut()})}return{init}})();

 const Final=(()=>{const panel=$('#final-question-panel'),opts=$('#final-options'),msg=$('#final-message'),more=$('#more-btn'),surprise=$('#surprise');function question(){opts.innerHTML='';SITE_CONFIG.finalAnswerOptions.forEach(text=>{const b=document.createElement('button');b.type='button';b.className='final-option';b.textContent=text;b.addEventListener('click',()=>{ $$('.final-option').forEach(x=>x.classList.remove('is-selected'));b.classList.add('is-selected');setTimeout(()=>{panel.classList.add('hidden');msg.classList.remove('hidden');reveal(msg);setTimeout(()=>more.classList.remove('hidden'),reduced?100:1200)},reduced?120:650)});opts.appendChild(b)})}function constellation(){const c=$('#constellation');c.innerHTML='';[[8,70],[17,34],[27,55],[49,22],[64,44],[76,30],[89,66],[60,82],[38,86]].forEach(([x,y],i)=>{const d=document.createElement('span');d.className='dot';d.style.left=x+'%';d.style.top=y+'%';d.style.animationDelay=i*.15+'s';c.appendChild(d)})}function init(){more.addEventListener('click',()=>{more.classList.add('hidden');surprise.hidden=false;const s=SITE_CONFIG.secretMessage;$('.surprise-line').textContent=s;$('#today-date').textContent=new Date().toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'});const img=$('.photo-frame--final img');if(img)img.loading='eager';constellation();setTimeout(()=>surprise.scrollIntoView({behavior:reduced?'auto':'smooth',block:'center'}),40)})}return{init,question}})();

 const Sound=(()=>{const b=$('#sound-toggle'),a=$('#ambient-audio');function init(){b.addEventListener('click',async()=>{const on=b.getAttribute('aria-pressed')==='true';if(on){a.pause();b.setAttribute('aria-pressed','false');return}try{a.volume=.28;await a.play();b.setAttribute('aria-pressed','true')}catch{b.setAttribute('aria-pressed','false')}})}return{init}})();

 function personalize(){document.title=SITE_CONFIG.name;$('.pre-line').textContent=SITE_CONFIG.openingLine;$('.story-kicker').textContent=SITE_CONFIG.introHeader;$('.photo-caption').textContent=SITE_CONFIG.photoCaption;$('.final-eyebrow').textContent=`for ${SITE_CONFIG.name} —`;$('.final-question-panel h3').textContent=SITE_CONFIG.finalQuestion;$$('#final-message p').forEach((p,i)=>{if(SITE_CONFIG.finalMessage[i])p.textContent=SITE_CONFIG.finalMessage[i]});$$('img').forEach(img=>{if(img.src.includes('our-photo.jpg')){img.src=SITE_CONFIG.photo;img.alt=`A memory of ${SITE_CONFIG.name}`}})}
 function init(){personalize();ParticleField.init();Cursor.init();Opening.init();Journey.init();renderCards('#memory-grid',SITE_CONFIG.memoryCards,'memory-card');renderCards('#future-grid',SITE_CONFIG.futureCards,'future-card');Photo.init();Final.init();Sound.init();$('#story-continue').addEventListener('click',()=>goTo('scene-journey'));reveal($('#scene-dark'));setTimeout(()=>body.classList.add('is-scrollable'),900)}
 document.addEventListener('DOMContentLoaded',init);
})();